name: 'jaffle_shop'
version: '1.0.0'
# require-dbt-version: [">=0.16.0", "<0.17.0"]

profile: 'jaffle_shop'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

quoting:
  database: false
  identifier: false
  schema: false

models:
  transient: true
